name: Build

on:
  push:
    branches:
    - develop

jobs:
  build:
    uses: futuredapp/.github/.github/workflows/ios-selfhosted-build.yml@main
    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
